apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
spec:
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
        - name: node
          image: node:16
          imagePullPolicy: IfNotPresent
          command: ["bash", "-c"]
          args: ["tail -f /dev/null"]
          env:
            - name: workdir
              value: home
          resources:
            limits:
              cpu: 1
              memory: 512Mi
          ports:
            - containerPort: 3000
        - name: mysql
          image: mysql:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "123456"
          ports:
            - name: mysql
              containerPort: 3306
        - name: nginx
          image: nginx:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: nginx
              containerPort: 80
          volumeMounts: # 需要系统自定义
            - name: temp
              mountPath: /temp
      volumes: # 需要系统自定义
        - name: temp
          hostPath:
            path: /usr/local/temp
